DELETE http://localhost:3001/api/people/647f9c1e705f2bf4fb4ad968
###
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "James Franco",
    "number": "5555-55555555"
}